baseURL: http://mouton.io/
languageCode: en-us
title: Hugo Fresh Theme
theme: hugo-fresh
publishDir: docs

params:
  hero:
    tagline: Mouton
    subTagline: The world's easiest presentation builder.
    buttonText: Build your own!
    image: illustrations/worker.svg
  navbar:
    buttonText: Sign up
    logo:
      src: logos/fresh.svg
      alt: Main navbar logo
    links:
    - text: Features
      url: /
    - text: Pricing
      url: /
  features:
    tagline: Presentations nowadays are dull and monotonous.
    subTagline: Let's change that! We are building a web-based editor to unleash your creativity and your desire to make the best presentations ever.
    panels:
    - title: Online Web Environment
      image: illustrations/icons/laptop-globe.svg
      text: Create astonishing slides with web technologies.
      button:
        text: Learn More
        url: /
      delay: 1
    - title: Present everywhere.
      image: illustrations/icons/mouse-globe.svg
      text: Create once, show everywhere.
      button:
        text: Learn More
        url: /
      delay: 2
    - title: Responsive plugins
      image: illustrations/icons/plug-cloud.svg
      text: Featuring the latest web innovations!
      button:
        text: Learn More
        url: /
      delay: 3
  sellingPoints:
    tagline: Content first. Audience second. Presenter third.
    points:
    - title: Content first
      description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: laptop-globe
    - title: Audience second
      description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: doc-sync
    - title: Presenter third
      description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: mobile-feed
  platform:
    image: illustrations/mockups/app-mockup.png
    tagline: One Platform to rule them All
    subTagline: Lorem ipsum sit dolor amet is a dummy text used by typography industry
    buttonText: Get Started
  clients:
    tagline: Presenter third
    subTagline: Lorem ipsum sit dolor amet is a dummy text used by typography industry
    clientExamples:
    - name: Irma Walters
      position: Accountant
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      image: 1.png
    - name: John Bradley
      position: Financial Analyst
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      image: 2.png
    - name: Gary Blackman
      position: HR Manager
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      image: 3.png
  contact:
    tagline: Drop us a line or two!
  footer:
    image: fresh-white.svg
    columns:
    - title: Product
      links:
      - name: Discover features
        url: "#"
      - name: Why choose our Product?
        url: "#"
      - name: Compare features
        url: "#"
      - name: Our Roadmap
        url: "#"
      - name: Request features
        url: "#"
    - title: Docs
      links:
      - name: Get Started
        url: "#"
      - name: User guides
        url: "#"
      - name: Admin guide
        url: "#"
      - name: Developers
        url: "#"
    - title: Blogroll
      links:
      - name: Latest News
        url: "#"
      - name: Tech articles
        url: "#"
      - name: Video Blog
        url: "#"
    followUs:
    - icon: github
      url: "https://github.com/lucperkins"
    - icon: dribbble
      url: "#"
    - icon: facebook
      url: "#"
    - icon: twitter
      url: "https://twitter.com/lucperkins"
    - icon: bitbucket
      url: "#"

